### Signup
POST http://localhost:5000/api/auth/signup
Content-Type: application/json

{
    "name": "Ravi",
    "email": "ravitejasalva976@gmail.com",
    "phone": "+1234567652",
    "password": "securepassword123"
}

### Send OTP (if needed to resend)
POST http://localhost:5000/api/auth/send-otp
Content-Type: application/json

{
    "phone": "+1234567890"
}

### Verify OTP
POST http://localhost:5000/api/auth/verify-otp
Content-Type: application/json

{
    "phone": "+1234567890",
    "otp": "820432"
}